### PR TITLE
Norman Proxy Support

### PR DESCRIPTION
**Pull request by jordanjean**
This Pull Request introduces proxy support for the Rancher Norman API.

### CODE REVIEW

**Comment by rawmind0** [comment]
Hi @jordanjean, have you modified directly the vendor file?? I think this change is not done at norman repo. The proper way to do it should be submit this PR at norman repo and then update module version here.

**Comment by jordanjean** [comment]
Hi @rawmind0, yes I opened a PR at the Norman repo (https://github.com/rancher/norman/pull/329). Once it is merged, I could update the module version and remove the changes made to the vendor file.

**Comment by rawmind0** [comment]
Cool, thanks.

**Comment by jordanjean** [comment]
Hi, the PR introducing proxy support for the Norman dependency is merged. I updated the module version here.

**Review by rawmind0 — CHANGES_REQUESTED** [review]
@jordanjean , you'd need to also update vendor files and include them in the PR, `GO111MODULE=on go mod vendor`

**Comment by jordanjean** [comment]
@rawmind0, vendor files updated.

**Comment by rawmind0** [comment]
@jordanjean , could you please resolve conflicts??

**Comment by jordanjean** [comment]
@rawmind0, for sure, branch rebased !

**Review by rawmind0 — APPROVED** [review]

**Review by rawmind0 — APPROVED** [review]
Thanks @jordanjean 

LGTM

**Pull request merged**
