### PR TITLE
feat(cloud-provider-azure): security_group_resource_group cloud config

### PR DESCRIPTION
**Pull request by aslafy-z**
Implement missing `security_group_resource_group` cloud-config value for Azure cloud provider in rke_config.

Depends on https://github.com/rancher/rke/pull/2578
Depends on https://github.com/rancher/types/pull/1198

### CODE REVIEW

**Review by rawmind0 — CHANGES_REQUESTED** [review]
@aslafy-z , PR building is failing, field `SecurityGroupResourceGroup` field doesn't exist at `AzureCloudProvider` struct

```
== Running testing...
--
328 | go test "./rancher2" \|\| exit 1
329 | # github.com/terraform-providers/terraform-provider-rancher2/rancher2 [github.com/terraform-providers/terraform-provider-rancher2/rancher2.test]
330 | rancher2/structure_cluster_rke_config_cloud_provider_azure.go:109:11: in.SecurityGroupResourceGroup undefined (type *"github.com/rancher/rancher/pkg/client/generated/management/v3".AzureCloudProvider has no field or method SecurityGroupResourceGroup)
331 | rancher2/structure_cluster_rke_config_cloud_provider_azure.go:110:44: in.SecurityGroupResourceGroup undefined (type *"github.com/rancher/rancher/pkg/client/generated/management/v3".AzureCloudProvider has no field or method SecurityGroupResourceGroup)
332 | rancher2/structure_cluster_rke_config_cloud_provider_azure.go:237:6: obj.SecurityGroupResourceGroup undefined (type *"github.com/rancher/rancher/pkg/client/generated/management/v3".AzureCloudProvider has no field or method SecurityGroupResourceGroup)
333 | rancher2/structure_cluster_rke_config_cloud_provider_azure_test.go:40:3: unknown field 'SecurityGroupResourceGroup' in struct literal of type "github.com/rancher/rancher/pkg/client/generated/management/v3".AzureCloudProvider
334 | FAIL	github.com/terraform-providers/terraform-provider-rancher2/rancher2 [build failed]
335 | FAIL
336 | make: *** [GNUmakefile:26: test] Error 1
```

**Comment by aslafy-z** [comment]
@rawmind0 Seen it, I opened a PR at https://github.com/rancher/types/pull/1198 to implement this field at the source of the generated types. Let me know if it's not sufficient.

**Comment by rawmind0** [comment]
@aslafy-z , PR https://github.com/rancher/types/pull/1198 is also failing to build. 

Anyway, this is not the right place where to add this new field. Rancher 2.5 is getting rke_types from [rke](https://github.com/rancher/rke), so PR should be submitted at it,  https://github.com/rancher/rke/blob/master/types/rke_types.go#L759 . Once this is done, another PR at Rancher should be submitted, generating go client bindings including  new added field

**Comment by aslafy-z** [comment]
@rawmind0 I also opened a PR at https://github.com/rancher/rke/pull/2578, tests passes.
Once it's merged, I will open the PR at r/r. Closing this one.
Thank you for the head-up.

**Pull request closed without merging**
