### PR TITLE
Change default image to 20-04

### PR DESCRIPTION
**Pull request by felipe-colussi**
## Problem

During tests we found a problem with  the `ubuntu-22-04-x64`, wile creating the downstream cluster it would get stuck after  `Installing Docker from: https://releases.rancher.com/install-docker/24.0.sh`     with one of  the following errors: 

* Error creating machine: Error runing "sudo apt-get update": ssh command error: command: sudo apt-get update err: exit status 100 output: Hit:1http://archive.ubuntu.com/ubuntu jammy in release 

* Error creating machine: Error Installing docker:
 
Those errors were happening 100% of the times (UI or TF) on 2.7  and also were happening on 2.8 (sometimes it worked on that one). 

 
## Solution

 
 Wile testing with  `ubuntu-20-04-x64`  we didn't get the error. 
For safety reasons we decided to change the image back to 20-04

 
## Testing

Create machine using TF. 

### Manual Testing

Create machine using TF. 

### Automated Testing

None 

### Regressions Considerations

main.tf
```terraform

terraform {
  required_providers {
    rancher2 = {
      source  = "terraform.local/local/rancher2"
      version = "4.0.0-rc4"
    }
  }
}

provider "rancher2" {
  api_url   = "<REDACTED>"
  token_key = "<REDACTED>"
  insecure  = true
}


resource "rancher2_node_template" "rancher2_node_template" {
  name = "qa-testing-jkeslar-plz-deletee"
  digitalocean_config {
    access_token  = "<REDACTED>"
    ipv6 = false
    monitoring = false
    private_networking = false
    region = "nyc3"
    size = "s-2vcpu-4gb-intel"
    ssh_key_fingerprint=	""
    ssh_port = "22"
    ssh_user =	"root"
    tags =""
    userdata= ""
  }
}



resource "rancher2_cluster" "rancher2_cluster" {
  depends_on = [rancher2_node_template.rancher2_node_template]
  name       = "jkeslar-qa-testing-plz-deletee"
  rke_config {
    kubernetes_version = "v1.27.6-rancher1-1"
    network {
      plugin = "canal"
    }
  }
}

resource "rancher2_node_pool" "pool1" {
  depends_on       = [rancher2_cluster.rancher2_cluster]
  cluster_id       = rancher2_cluster.rancher2_cluster.id
  name             = "pool1"
  hostname_prefix  = "jkeslar-pool1-"
  node_template_id = rancher2_node_template.rancher2_node_template.id
  quantity         = 1
  control_plane    = true
  etcd             = true
  worker           = true
}

```

### CODE REVIEW

**Review by snasovich — CHANGES_REQUESTED** [review]
We currently only list 22.04 as the supported version on latest support matrix (e.g. https://www.suse.com/suse-rancher/support-matrix/all-supported-versions/rancher-v2-7-9/). So we shouldn't be switching the default to 20.04.

We need to figure out why 20.04 is not working and probably file a separate issue for that.

**Comment by a-blender** [comment]
@snasovich Do you mean why 22.04 isn't working? ;)

But yeah, agree. Is apt not installed by default on 22-04 or something and that's why the cmd is failing? I'd also be curious who condoned regressing the default image.

**Review by a-blender — CHANGES_REQUESTED** [review]
@snasovich Do you mean why 22.04 isn't working? ;)

But yeah, agree. Is apt not installed by default on 22-04 or something and that's why the cmd is failing? I'd also be curious who condoned regressing the default image.

**Comment by kkaempf** [comment]
closing stale PRs.
If you still intend to work on this, please reopen.

**Pull request closed without merging**
