### PR TITLE
Add bootFromVolume for openstack node template

### LINKED ISSUE #561: Add support for boot_from_volume and relevant attributes for openstack_config for node_template
When using the rancher ui one can create a openstack node template that boots vms from volume. This is not possible via the provider. Related attributes:
- bootFromVolume
- volumeSize
- volumeType
- volumeId
- volumeName
- volumeDevicePath

I'll make a PR for this soon

### PR DESCRIPTION
**Pull request by nikParasyr**
Add support on openstack_config on node template to enable booting
from volume.

Close #561

### CODE REVIEW

**Review by rawmind0 — CHANGES_REQUESTED** [review]
Thanks for the PR @nikParasyr 

PR looks good but CHANGELOG.md is not updated. Could you please also update CHANGELOG.md accordingly??

**Comment by nikParasyr** [comment]
@rawmind0 Hi. Updated the changelog and also rebased etc.
Added it as enhancement

**Comment by nikParasyr** [comment]
ci got killed i think

**Comment by rawmind0** [comment]
> ci got killed i think

I've restarted it :)

**Review by rawmind0 — APPROVED** [review]
LGTM

**Pull request merged**
