### PR TITLE
Add AKS node pool new options

### LINKED ISSUE #1115: [BUG] rancher2 provider does NOT currently support configuring taints, labels, and maxSurge node pool values for AKS clusters
With the recent [AKS enhancements](https://github.com/rancher/dashboard/issues/8073), to allow users to configure taints, labels and maxSurge values for node pools, there seems to be missing functionality in rancher2, with regards to these enhancements, which are expected to be supported, as the feature has come `to-test`.  This ticket was created to track the integration of these enhancements into rancher2 provider.

---

### Rancher Server Setup
- Rancher version: `v2.7-8e049e524d5d03fab49b17bf92c767ca5797b49d-head`
- Installation option (Docker install/Helm Chart): `HA Helm`
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): local `RKE` cluster running k8s `v1.25.9`
- Proxy/Cert Details: `byo-valid`

### Information about the Cluster
- Kubernetes version: `v1.25.6`
- Cluster Type (Local/Downstream): Downstream rancher2 provisioned AKS cluster

### User Information
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
`admin`

### Provider Information
- What is the version of the Rancher v2 Terraform Provider in use? `v3.0.0`
- What is the version of Terraform in use? `v1.3.7`

### Describe the bug
When attempting to configure taints, labels and maxSurge values for node pools in a downstream rancher2 provisioned AKS cluster, `terraform apply` results in `not expected to be here`, for these fields.

### To Reproduce
1. Fresh install of rancher v2.7-head
2. Using rancher2 provider `v3.0.0` and terraform `v1.3.7`, attempt to provision a downstream AKS cluster with taints, labels and maxSurge values configured for node pools
3. Reproduced

### Actual Result
For all the mentioned fields - [`taints`, `labels`, `max_surge`] - rancher2 provider responds with `Error: Unsupported argument`

An argument named "`taints || labels || max_surge`" is not expected here.

### Expected Result
Rancher2 provider should successfully create these resouces, as outlined in the `main.tf` file

### Screenshots
Screenshot 2023-05-04 at 11 55 02 AM

### PR DESCRIPTION
**Pull request by mjura**
Add labels, taints and max surge options to Node Pool

Fix: https://github.com/rancher/terraform-provider-rancher2/issues/1115

### CODE REVIEW

**Review by richardcase — APPROVED** [review]
LGTM

**Review by furkatgofurov7 — APPROVED** [review]
LGTM

Maybe it is worth mentioning why the go mod changes are needed (TL;DR: the commit hash used for rancher/pkg/apis and rancher/pkg/client were behind and modules update to latest commit hash was needed to make new fields available in the schema) and link the PR which added these new fields to the schema for easier review/understanding

**Review by a-blender — CHANGES_REQUESTED** [review]
@mjura Looks good, but please

1. Add new fields and data types to the docs
2. Make sure to fill out the PR template, and add steps for how you did manual / automated testing to make sure this works in aks.

**Comment by mjura** [comment]
> @mjura Looks good, but please
> 
> 1. Add new fields and data types to the docs

I have added options to documentation

> 2. Make sure to fill out the PR template, and add steps for how you did manual / automated testing to make sure this works in aks.

Example was added and tested with AKS

It is ready to merge

**Review by a-blender — APPROVED** [review]
Looks great @mjura! Go ahead and merge once CI passes.

**Pull request merged**
