### PR TITLE
Add ForceNew for immutable template binding fields

### LINKED ISSUE #379: Fix ForceNew behaviour on cluster_role_template_binding and project_role_template_binding schemas
name, group_id, group_principal_id, user_id and user_principal_id are immutable on cluster_role_template_bindings and project_role_template_bindings and should ForceNew

gz#13065

### PR DESCRIPTION
**Pull request by axeal**
Closes #379

### CODE REVIEW

**Review by rawmind0 — COMMENTED** [review]
Agreed `name` argument update. I've also noticed a possible related error, `role_template_id` shouldn't have `ForceNew: true` . Same for cluster and project scopes.

Other arguments, `group_id`, `group_principal_id` and `user_id` are not immutable. All of them can be updated from rancher API, cluster https://<RANCHER_URL>/v3/schemas/clusterRoleTemplateBinding , project https://<RANCHER_URL>/v3/schemas/projectRoleTemplateBinding

**Comment by axeal** [comment]
@rawmind0 I have removed ForceNew for role_template_id

Per https://<RANCHER_URL>/v3/schemas/clusterRoleTemplateBinding and https://<RANCHER_URL>/v3/schemas/projectRoleTemplateBinding groupId, groupPrincipalId, userId and userPrincipalId have `update: false` and are immutable unless my understanding of those schema endpoints is incorrect?

**Comment by rawmind0** [comment]
@axeal , what rancher version are you using to check?? It seems these fields can be updated on rancher v2.3.x, but not in rancher v2.4.x... 

```
"resourceFields": {
	"annotations": {
		"create": true,
		"nullable": true,
		"type": "map[string]",
		"update": true
	},
	"clusterId": {
		"create": true,
		"nullable": true,
		"required": true,
		"type": "reference[cluster]",
		"update": true
	},
	"created": {
		"create": false,
		"nullable": true,
		"type": "date",
		"update": false
	},
	"creatorId": {
		"create": false,
		"type": "reference[/v3/schemas/user]",
		"update": false
	},
	"groupId": {
		"create": true,
		"nullable": true,
		"type": "reference[group]",
		"update": true
	},
	"groupPrincipalId": {
		"create": true,
		"nullable": true,
		"type": "reference[principal]",
		"update": true
	},
	"labels": {
		"create": true,
		"nullable": true,
		"type": "map[string]",
		"update": true
	},
	"name": {
		"create": true,
		"nullable": true,
		"type": "dnsLabel",
		"update": false
	},
	"namespaceId": {
		"create": true,
		"nullable": true,
		"type": "reference[/v3/clusters/schemas/namespace]",
		"update": false
	},
	"ownerReferences": {
		"create": false,
		"nullable": true,
		"type": "array[ownerReference]",
		"update": false
	},
	"removed": {
		"create": false,
		"nullable": true,
		"type": "date",
		"update": false
	},
	"roleTemplateId": {
		"create": true,
		"nullable": true,
		"required": true,
		"type": "reference[roleTemplate]",
		"update": true
	},
	"userId": {
		"create": true,
		"nullable": true,
		"type": "reference[user]",
		"update": true
	},
	"userPrincipalId": {
		"create": true,
		"nullable": true,
		"type": "reference[principal]",
		"update": true
	},
	"uuid": {
		"create": false,
		"nullable": true,
		"type": "string",
		"update": false
	}
}
```

**Comment by axeal** [comment]
@rawmind0 Ah ok, yes I am using v2.4.5

**Comment by rawmind0** [comment]
Due to these fields can be updated on rancher v2.3.x, but not in rancher v2.4.x, PR is not ideal. This should be addressed defining a [`CustomizeDiff`](https://www.terraform.io/docs/extend/resources/customizing-differences.html) func on template bindings,  forcing new object on fields change, just if rancher version is up to 2.4.0

**Comment by rawmind0** [comment]
@axeal , any update here??

**Comment by rawmind0** [comment]
@axeal , could you please rebase PR to resolve conflicts?? As on new rancher v.2.4 and v2.5, fields are immutables and `forceNew` would be compatible with v2.3, i amend my previous comment and once conflicts are resolved when can merge as PR is.

**Comment by axeal** [comment]
@rawmind0 I screwed up the rebase, so creating new branch afresh. Closing this PR out and will open a new one.

**Comment by axeal** [comment]
Opened #507

**Pull request closed without merging**
