### PR TITLE
Inject more global values in apps based on dashboard

### PR DESCRIPTION
**Pull request by mouellet**
Signed-off-by: Mathieu Ouellet <mathieu.ouellet@energumen.io>

### CODE REVIEW

**Comment by a-blender** [comment]
Could you add a more detailed description? Is there a GH issue?

**Comment by mouellet** [comment]
@a-blender i’ll do! Still in draft as I haven’t been able to test the Windows part yet…

**Comment by a-blender** [comment]
@mouellet What's the status on this? Is there a GH issue to track it? Has this been reproduced or is just an enhancement brought up by the UI team?

**Comment by kkaempf** [comment]
closing stale PRs.
If you still intend to work on this, please reopen.

**Pull request closed without merging**
