### PR TITLE
Add Outscale support for node driver

### PR DESCRIPTION
**Pull request by outscale-mdr**
Hello Rancher team,

As part of a series of PR to support [Outscale](https://en.outscale.com/) as a cloud provider:
- quickstart: https://github.com/rancher/quickstart/pull/207
- docs: https://github.com/rancher/docs/pull/4138
- rancher/rancher: https://github.com/rancher/rancher/pull/38195

Here is our contribution to add node driver information into the rancher server.

Best regards,
Maxime

Issue: https://github.com/rancher/rancher/issues/37886

### CODE REVIEW

**Comment by outscale-mdr** [comment]
CI is broken on the master branch

**Comment by jakefhyde** [comment]
Hi @outscale-mdr, we've merged https://github.com/rancher/rancher/pull/38195, and will merge this PR after releasing version v1.24.1 of the tf provider (expected to be released within the next week).

**Comment by outscale-mdr** [comment]
Hello @jakefhyde, thank you for the update !

**Comment by a-blender** [comment]
Terraform [v1.24.1](https://registry.terraform.io/providers/rancher/rancher2/latest/docs/resources/registry) has been released

**Review by a-blender — APPROVED** [review]
LGTM! I'd prefer if a 2 node node driver cluster deployed onto Outscale were tested on rancher 2.6.8 but otherwise ok to merge

**Review by HarrisonWAffel — APPROVED** [review]

**Review by HarrisonWAffel — APPROVED** [review]

**Pull request merged**
