### PR TITLE
ignore existing eks node_groups, labels, and tags if it is an imported cluster

### PR DESCRIPTION
**Pull request by kalinon**
Should solve rancher/terraform-provider-rancher2#800

### CODE REVIEW

**Comment by thedadams** [comment]
I don't think this fixes the problem. If these fields are left out, then the will be passed as `nil` to the client. The problem is between the client and Rancher.

**Comment by kalinon** [comment]
It does, because rancher auto imports changes from AWS on its side. By passing null, it doesn't update it. The rancher controller will pull the values, but if it's defined it will see a Delta in the configs and perform a change.

**Comment by thedadams** [comment]
Sorry, let me be more clear.

If you leave these items out of the terraform file or if you make the change that you're making here, then you have achieved the same thing. So, if you put these items in the terraform file, then your change will take them out.

There is still a problem after that. For example, if you take out the `nodegroups`, then the client that the terraform provider uses will still send `nodegroups: []`. And, if your EKS cluster has any nodegroups in it, they will be deleted (because there is a delta as you described).

So, this change will protect a user if they mistakenly put in the wrong items, but there is still the problem that I am describing that happens with the client.

**Comment by rawmind0** [comment]
The PR is incomplete. To fix the problem, the same logic has to be applied the the `flattenClusterEKSConfigV2` and to the `expandClusterEKSConfigV2` functions. 

Take a look how it's done at `aks_config_v2`, https://github.com/rancher/terraform-provider-rancher2/blob/master/rancher2/structure_cluster_aks_config_v2.go#L68 and 
https://github.com/rancher/terraform-provider-rancher2/blob/master/rancher2/structure_cluster_aks_config_v2.go#L241

**Comment by kalinon** [comment]
@rawmind0 i gave it a go! Please let me know if thats what you meant.

**Review by rawmind0 — CHANGES_REQUESTED** [review]
Thanks for the update @kalinon , but it wasn't what i meant. Let me try to explain better.

If the eks cluster is imported, just `cloud_credential_id, `name`, `region` and  `imported` arguments should be filled.  So the PR should treat this fields and as [mentioned](https://github.com/rancher/terraform-provider-rancher2/pull/843#issuecomment-1020028406), return if cluster is imported. The code should be something like that

```
	//FILL required arguments for imported eks cluster
	if v, ok := in["imported"].(bool); ok {
		obj.Imported = v
		if obj.Imported {
			// Return if the cluster is imported
			return obj
		}
	}
	// FILL the rest of the arguments for NON imported eks cluster
```

Also, the cluster docs should be updated for `eks_config_v2`, with something like that, https://registry.terraform.io/providers/rancher/rancher2/latest/docs/resources/cluster#aks_config_v2

**Comment by kalinon** [comment]
@rawmind0 ah, i better understand now. thanks. Let me fix that up.

**Comment by kkaempf** [comment]
closing stale PRs.
If you still intend to work on this, please reopen.

**Pull request closed without merging**
