### PR TITLE
Updated rancher2_notifier resource to be replaced on update

### PR DESCRIPTION
**Pull request by rawmind0**
Issue https://github.com/rancher/terraform-provider-rancher2/issues/382

### CODE REVIEW

**Review by nickgerace — APPROVED** [review]
~~The logic LGTM, but what if users want these features?~~
EDIT: this was not supposed to be an approval... thanks GitHub + TAB + ENTER

**Review by nickgerace — COMMENTED** [review]
The logic LGTM, but what if users want these features?

**Comment by rawmind0** [comment]
> The logic LGTM, but what if users want these features?

@nickgerace , what user features do you mean?? 

The root cause of the issue is that the rancher2_notifier is merged instead of being replaced at Rancher API. The merge is not working fine on some scenarios due to null or empty fields are omitted at json marshal/unmarshal, so once any of this field is set, it can't be nullified nor emptied using the API. The PR is just forcing to replace the resource instead of update it.

**Comment by nickgerace** [comment]
> @nickgerace , what user features do you mean??

The providers themselves, but reading your message, it makes sense now.

> The root cause of the issue is that the rancher2_notifier is merged instead of being replaced at Rancher API. The merge is not working fine on some scenarios due to null or empty fields are omitted at json marshal/unmarshal, so once any of this field is set, it can't be nullified nor emptied using the API. The PR is just forcing to replace the resource instead of update it.

Ah gotcha. Thanks!

**Review by superseb — APPROVED** [review]

**Pull request merged**
