### PR TITLE
Added rancher2_cluster support to gke config v2

### PR DESCRIPTION
**Pull request by rawmind0**
Also added support for Rancher 2.5.8

Issue https://github.com/rancher/rancher/issues/31295

PR is now supporting Rancher v2.5.8-rc2. It should be updated before merge, once Rancher v2.5.8 is released

### CODE REVIEW

**Comment by rawmind0** [comment]
Updated PR to support Rancher v2.5.8-rc8.

Attaching tfp custom binaries to be tested:
* [terraform-provider-rancher2_linux_amd64.gz](https://github.com/rancher/terraform-provider-rancher2/files/6358291/terraform-provider-rancher2_linux_amd64.gz)
* [terraform-provider-rancher2_windows_amd64.exe.gz](https://github.com/rancher/terraform-provider-rancher2/files/6358292/terraform-provider-rancher2_windows_amd64.exe.gz)
* [terraform-provider-rancher2_darwin_amd64.gz](https://github.com/rancher/terraform-provider-rancher2/files/6358289/terraform-provider-rancher2_darwin_amd64.gz)

To use custom binary, download proper architecture archive, decompress it and use it to overwrite tf provider binary.

**Comment by rawmind0** [comment]
* Updated PR to support Rancher v2.5.8-rc11.
* Added support to google cloud credentials
* Fixed provder crash when adding the master_authorized_networks_config block with empty values

Attaching tfp custom binaries to be tested:
* [terraform-provider-rancher2_darwin_amd64.gz](https://github.com/rancher/terraform-provider-rancher2/files/6395475/terraform-provider-rancher2_darwin_amd64.gz)
* [terraform-provider-rancher2_linux_amd64.gz](https://github.com/rancher/terraform-provider-rancher2/files/6395476/terraform-provider-rancher2_linux_amd64.gz)
* [terraform-provider-rancher2_windows_amd64.exe.gz](https://github.com/rancher/terraform-provider-rancher2/files/6395477/terraform-provider-rancher2_windows_amd64.exe.gz)

To use custom binary, download proper architecture archive, decompress it and use it to overwrite tf provider binary.

**Comment by rawmind0** [comment]
* Updated PR to support Rancher v2.5.8, already released
* Patched provider to workaround issues https://github.com/rancher/rancher/issues/32553 and https://github.com/rancher/rancher/issues/32440
* Routed-based GKE clusters are not supported due to issue https://github.com/rancher/rancher/issues/32585

Attaching tfp custom binaries to be tested:
* [terraform-provider-rancher2_darwin_amd64.gz](https://github.com/rancher/terraform-provider-rancher2/files/6437194/terraform-provider-rancher2_darwin_amd64.gz)
* [terraform-provider-rancher2_linux_amd64.gz](https://github.com/rancher/terraform-provider-rancher2/files/6437195/terraform-provider-rancher2_linux_amd64.gz)
* [terraform-provider-rancher2_windows_amd64.exe.gz](https://github.com/rancher/terraform-provider-rancher2/files/6437196/terraform-provider-rancher2_windows_amd64.exe.gz)

To use custom binary, download proper architecture archive, decompress it and use it to overwrite tf provider binary.

Config used to test GKE clusters:
* Imported:
```
resource "rancher2_cloud_credential" "foo-google" {
  name = "foo-google"
  description= "Terraform cloudCredential acceptance test"
  google_credential_config {
    auth_encoded_json = file(<GOOGLE_AUTH_ENCODED_JSON>)
  }
}

resource "rancher2_cluster" "foo" {
  name = "foo"
  description = "Foo rancher2 imported GKE cluster"
  gke_config_v2 {
    name = "foo"
    google_credential_secret = rancher2_cloud_credential.foo-google.id
    region = <REGION> # Zone argument could also be used instead of region
    project_id = <PROJECT_ID>
    imported = true
  }
}
```
* Create new
```
resource "rancher2_cloud_credential" "foo-google" {
  name = "foo-google"
  description= "Terraform cloudCredential acceptance test"
  google_credential_config {
    auth_encoded_json = file(<GOOGLE_AUTH_ENCODED_JSON>)
  }
}

resource "rancher2_cluster" "foo" {
  name = "foo"
  description = "Terraform GKE cluster"
  gke_config_v2 {
    name = "foo"
    google_credential_secret = rancher2_cloud_credential.foo-google.id
    region = <REGION> # Zone argument could also be used instead of region
    project_id = <PROJECT_ID>
    kubernetes_version = <K8S_VERSION>
    network = <NETWORK>
    subnetwork = <SUBNET>
    node_pools {
      initial_node_count = 1
      max_pods_constraint = 110
      name = <NODE_POOL_NAME>
      version = <VERSION>
    }
  }
}
```

```

**Review by superseb — APPROVED** [review]

**Comment by rawmind0** [comment]
The feature is available at tfp v1.14.0

**Pull request merged**
