### PR TITLE
Adding default_pod_security_admission_configuration_template_name option

### PR DESCRIPTION
**Pull request by gregsidelinger**
## Solution
Added option to set the Rancher PSA template.  When this option is present Rancher will update kube-apiserver-arg list and add  - - admission-control-config-file=/etc/rancher/rke2/config/rancher-psact.yaml.  This patch does not ignore this option and will cause Terraform to want to remove the setting on the next run.  Was not sure how to ignore the diff so for right now I added that option to my machine-global-config settings.

### CODE REVIEW

**Comment by a-blender** [comment]
@gregsidelinger Hi! Can you please resolve the conflicts?

**Comment by a-blender** [comment]
@gregsidelinger Apologies, thank you. These changes are actually already being implemented in https://github.com/rancher/terraform-provider-rancher2/pull/1119. Once that code has been fully tested and merged, this PR can be closed as a duplicate.

**Comment by lazyfrosch** [comment]
Isn't that a duplicate of #1117 ?

**Comment by a-blender** [comment]
@lazyfrosch Yes sorry, this is a duplicate I will close it.

**Pull request closed without merging**
