### PR TITLE
Do not sort mirror endpoints because ordering could matter

### PR DESCRIPTION
**Pull request by gregsidelinger**
Signed-off-by: Greg Sidelinger <gate@ilive4code.net>

Quick fix to https://github.com/rancher/terraform-provider-rancher2/issues/1028

### CODE REVIEW

**Comment by gregsidelinger** [comment]
I've tested this and the order of the endpoints that get configured in the containerd/config.toml now match what terraform is setting.

**Review by a-blender — APPROVED** [review]
LGTM thank you @gregsidelinger

**Review by jakefhyde — APPROVED** [review]
Thanks for the contribution, LGTM!

**Comment by gregsidelinger** [comment]
Any chance this PR is going to get merged to make the next release?

**Pull request merged**
