### PR TITLE
Updated RKE config machine pool schema and structure

### LINKED ISSUE #1249: [RFE] Support Elemental or allow machineconfig with another apiversion
### Is your feature request related to a problem? Please describe.

Can't use terraform to provision our elemental teal rke2 cluster. https://elemental.docs.rancher.com/

### Describe the solution you'd like

Add support to provision provision clusters, create all the resources with elemental, create isos etc.

### Describe alternatives you've considered

I am currently creating manifests on the local cluster to get around this but having problems. 

### Additional context

image
image

### PR DESCRIPTION
**Pull request by gylli251**
## Issue: 

https://github.com/rancher/terraform-provider-rancher2/issues/1249
 
## Problem

When you are creating an elemental cluster via terraform the apiversion which rancherv2 cluster uses by default for the machine_config is wrong. You need "elemental.cattle.io/v1beta1".
 
## Solution

Added api_version as an option for machine_config via the schema and structure code. so we can do this:
image

 
## Testing

I have no idea how to test properly not sure if its needed since these changes are very minor.

### Manual Testing

Tested the provider myself and have created/destroyed/made changes in place, more than 10 clusters without fault.

### Regressions Considerations

My first real merge request on github, please advise me if you feel like i can do stuff better!

### CODE REVIEW

**Comment by gylli251** [comment]
There seems to be something wrong with the build... not sure if its my fault or not.

**Comment by a-blender** [comment]
@gylli251 Nah, appears to be a flaky test. I restarted it.

**Review by a-blender — APPROVED** [review]
Thanks for opening this PR! Looks straightforward to be and since it's an optional field, won't break existing cluster schemas. Lgtm. To answer your question - it will need to be tested by QA, please add a test template to the GH issue outlining test steps for the following cases
1. Provisioning an RKE2 cluster with `api_version` set.
3. Upgrading the TF version of an existing RKE2 cluster to the next Terraform RC (likely 4.0.0-rc4) to make sure there are no issues / errors.

**Review by mjura — APPROVED** [review]
lgtm

**Review by a-blender — DISMISSED** [review]
Can you please add the new field to the docs?

**Review by richardcase — CHANGES_REQUESTED** [review]
Looks good to me. Just the comment from @a-blender outstanding:

> Can you please add the new field to the docs?

@gylli251 - would you be able to add the field to the docs?

**Comment by kkaempf** [comment]
ping @gylli251 👆🏻

**Comment by gylli251** [comment]
I think i added documentation that is sufficient. please let me know if more is needed.

**Review by richardcase — APPROVED** [review]

**Pull request merged**
