### PR TITLE
Terraform v0.12.0 support

### PR DESCRIPTION
**Pull request by drpebcak**

### CODE REVIEW

**Comment by drpebcak** [comment]
The tests all pass locally. Not sure if there is some issue with the travis config.

**Comment by drpebcak** [comment]
Also, it wasn't entirely clear to me if this project is still using trash or not. If not, I can redo this with modules.

**Comment by rawmind0** [comment]
@drpebcak, build is failing due to some libraries are not found on vendor folder. May be you have installed these libraries locally and that's why tests are passing locally??

Anyway, this project is not using trash anymore, could you please redo this with modules??

**Comment by drpebcak** [comment]
Looks like this failed a test, but that's rancher functionality it failed with, not anything to do with the provider. Looks like master also failed with the same error.

@rawmind0 take another look.

**Comment by rawmind0** [comment]
Looks much better. The failed step on acceptance tests is know, it occurs with setting resource due to a bug on rancher v2.2.x. It will be fixed on rancher v2.3

Fixes #14

**Review by rawmind0 — APPROVED** [review]
LGTM

**Pull request merged**
