### PR TITLE
Allow setting vmAffinity for Harvester clusters

### PR DESCRIPTION
**Pull request by buffstyles**
Issue: rancher/terraform-provider-rancher2#1009

### CODE REVIEW

**Comment by buffstyles** [comment]
@annablender Hello. I don't know who is maintaining this project, but could you help with the review and suggest whether it is possible to add this feature to the next release?

**Comment by joeyloman** [comment]
Hi, I need this patch as well since I want to automate the creation of topology aware RKE2 clusters on top of Harvester. I tested this code against Rancher v2.6.9 and Harvester v1.1.1 and it works like it should. So please merge this asap.

**Comment by futuretea** [comment]
LGTM

**Review by a-blender — APPROVED** [review]
I confirmed node affinity is available in rancher `2.6.11-rc2` and should be in `2.7` so Terraform support for this issue needs to go into both `master` and back ported to `release/v2,` which is aligned with Rancher minor version 2.6 for backend support to show up in the next Rancher 2.6 release.

Note: There are currently no Harvester Terraform provider expander/flattener tests to add this new field to and those tests would be a good candidate for autogeneration.

Please review @jakefhyde @HarrisonWAffel

**Review by HarrisonWAffel — APPROVED** [review]
Looks good, we should make sure we catch the missing tests in future commits

**Pull request merged**
